# Generated by Django 3.0.3 on 2020-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, default='/images/car.jpg', null=True, upload_to='static/images'),
        ),
    ]
