# Generated by Django 3.0.3 on 2020-09-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200926_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, default='/images/car.jpg', null=True, upload_to=''),
        ),
    ]
